- import_role:
    name: httpd
  when: not mirmon_https

- import_role:
    name: httpd
  vars:
    httpd_tls: True
  when: mirmon_https

- name: Ensuring we have a document root for vhost
  file:
    path: /var/www/mirmon-status
    state: directory
    owner: "{{ mirmon_local_user }}"

- name: mirmon httpd vhost
  template:
    src: 100_mirmon_status.conf.j2
    dest: /etc/httpd/conf.d/100_mirmon_status.conf
    mode: 0644
  notify:
    - restart_httpd

- name: Configuring https for mirmon
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  notify:
    - restart_httpd
  with_items:
    - ssl-mirmon.conf
  when: mirmon_https  
   
- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ mirmon_public_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls
    - pki
  when: mirmon_https  

