- name: Ensuring we have local unprivileged user owning mirmon content
  user:
    name: "{{ mirmon_local_user }}"
    comment: "Local CentOS mirmon user"
    home: "/home/{{ mirmon_local_user }}-home/"

- name: Ensuring we have a place to store scripts (legacy compat)
  file:
    path: "/home/{{ mirmon_local_user }}-scripts"
    state: directory
    owner: "{{ mirmon_local_user }}"
    group: "{{ mirmon_local_user }}"

- name: Ensuring we have a place to store mirrorlists files
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mirmon_local_user }}"
    group: "{{ mirmon_local_user }}"
    setype: user_home_dir_t
    mode: 0755
  with_items:
    - "{{ mirmon_local_path }}"
    - "{{ mirmon_local_path }}/ipv4"
    - "{{ mirmon_local_path }}/ipv4/centos"
    - "{{ mirmon_local_path }}/ipv4/altarch"
    - "{{ mirmon_local_path }}/ipv6"
    - "{{ mirmon_local_path }}/ipv6/centos"
    - "{{ mirmon_local_path }}/ipv6/altarch"
    - "{{ mirmon_local_path }}/logs"

- name: Ensuring we can connect to mysql
  template:
    src: .my.cnf.j2
    dest: "/home/{{ mirmon_local_user }}-home/.my.cnf"
    owner: "{{ mirmon_local_user }}"
